### ISSUE TITLE
Blacklisted long URL (finance.yahoo.com)

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#50]
Hi. I am sometimes getting a "Blacklisted long URL" 400 error for some legitimate news sites. For example:

* https://finance.yahoo.com/m/a8255075-9607-30b7-a123-7ec4368f11ad/apple-iphone-estimates-keep.html?.tsrc=rss
* https://finance.yahoo.com/news/apple-is-making-your-i-phone-more-secure-to-fight-off-nation-state-hackers-180008035.html?.tsrc=rss

Can this site (and any other news sites) be removed from the blacklist?

**Comment by relrod** [comment]
If you come across any other false positives, please let us know, we should be able to take care of them. There's quite a bit of logic flow right now for blacklisting because attackers like using short URLs to try to phish victims' personal information. We do a fair bit to try to prevent it, and sometimes legitimate stuff can get caught in the trap.
