### ISSUE TITLE
Blacklisted long URL (crypto-news-flash.com)

### ISSUE THREAD

**Issue by impredicative** [dagd/dagd#53]
* [x] https://www.investing.com/news/stock-market-news/banco-bpm-repaid-125-billion-euros-of-ecb-loans--source-2961384
* [x] https://www.fxempire.com/news/article/banco-bpm-repaid-12-5-billion-euros-of-ecb-loans-source-1226282
* [ ] https://www.crypto-news-flash.com/crypto-lender-blockfi-files-for-bankruptcy-and-sues-sbf-for-575m-robinhood-shares-will-bitcoin-drop/
* [ ] https://www.crypto-news-flash.com/will-the-biggest-bitcoin-trust-with-635000-btc-fall-investors-face-trust-issues/?utm_source=rss&utm_medium=rss&utm_campaign=will-the-biggest-bitcoin-trust-with-635000-btc-fall-investors-face-trust-issues

**Comment by relrod** [comment]
The last two from a DNSBL, not us:

```
[root@dagd-app03 dagd-prod]# ./scripts/check-blacklist -u 'https://www.crypto-news-flash.com/crypto-lender-blockfi-files-for-bankruptcy-and-sues-sbf-for-575m-robinhood-shares-will-bitcoin-drop/'
[ERROR] The URL is blacklisted
Blacklist source: shorten.dnsbl
```

Specifically in this case, it's blocked by spamhaus: https://check.spamhaus.org/listed/?searchterm=crypto-news-flash.com

I would talk to them to get it delisted if it should be.

The first two are matching strings in our substring list which was added due to a phishing attack against a financial institution. I will try lifting it and see what happens.

re: #54 -- a few thoughts: I think user-agent isn't quite the way to do something like that. I would be more inclined to think about handing out API keys to heavy users of the service (this would be a manual process, I explicitly do not want to maintain an auth mechanism on the site). This would help you, but not people who set up your bot themselves. This might be an acceptable middle ground (and assuming your bot handles the 400 gracefully, I imagine that missing an occasional short URL and instead showing the long URL in that case, would be fine). It would likely have to do similar if it couldn't contact da.gd due to an outage or network blip anyway.

The other thing is #54 isn't quite trivial. It's *doable*, but it would require a database change. We run the blacklist logic both on access *and* creation of short URLs. This is so that if (for example) Google Safe Browsing or one of the DNSBLs adds a URL later, it automatically gets caught and we hopefully don't get reported about it. So #54 would require a database change so that it knew a short URL was created with a particular API key and that, at access time, it shouldn't run the blacklist logic. Again, doable, but it's not just a matter of "allow the URL to be created", there's some more to it.

I'm open to doing something like this, but I also think that these cases you're running into should be fairly rare. A quick grep of the access logs right now shows that for your useragent, the blacklist hit rate is under 2%.

```
# awk '/POST \/s.*impredicative/ {print $9}' da.gd-access_log* | sort | uniq -c
  14487 200
    276 400
```

**Comment by relrod** [comment]
> I also don't understand why it's the responsibility of dagd to police the internet; it's just a neutral URL shortener service.

I've already explained to you why the blacklist logic is in place. People use URL shorteners to create intricate redirect chains with the intent to phish credentials from innocent people. To steal money from people and ruin their lives.

When we catch wind of that, we go out of our way to stop it, for various reasons: One is to maintain a good relationship with our hosting provider and not get *their* IP space blacklisted on various services. Another is because I personally know people who have been attacked by phishing schemes like these, and I would not wish it on anyone. So, yes, if I can prevent someone from having that happen to them -- even if it means a rare false positive -- I am going to do it, unapologetically. If that is "policing the internet," then so be it.

If the error rate is too high, you are welcome to use a different service. Or fall back to a different service for particular URLs if you get an error from us. Or keep that particular URL unshortened. You have options.

This is a free service, and while I (and our team of volunteers that respond to and handle abuse reports every day) enjoy working on the service as a hobby, I'm not willing to sacrifice morals and watch innocent victims have their lives ruined for it. I'd sooner shut the site down entirely, but I've worked really hard to avoid having to do that. Again, because I enjoy working on the site as a side project, and I want to see it stay online.

We have numerous, large open source projects using the site every day with no issues, and we have for years, since the site started in 2011.

I'm not trying to be rude or mean, but you have to understand where we are coming from. We cannot simply lift the blacklist logic and let da.gd be used as a free-for-all with no attempt to curtail phishing attacks. For one, no reasonable hosting provider would allow that to happen, and secondly, even if they did, it goes against what I believe, after having seen people fall victims to the attacks we're trying to prevent.

I hope this helps you to understand.

**Comment by phuzion** [comment]
We do not intentionally block innocent sites and URLs. We block sites using the most specific tools we have at our disposal to address an issue.

Our blocking workflow tends to look something like this:
* Our abuse email receives a report, stating that a shorturl on our service redirects to somewhere malicious
* Our volunteer abuse team investigates the URL, confirms that it is malicious, and disables the single URL. Our bot then notifies us if there are other shorturls from the same IP address. If other shorturls in that list appear to be malicious, we block those.
* If most or all of the URLs from a single IP address appear to be malicious, we may opt to issue a single-IP-ban, which prevents that specific IP address from creating any new URLs.
* If many similar malicious URLs are created by multiple IP addresses, we may opt to add certain strings or regex's to the [denylist](https://github.com/dagd/dagd/blob/master/src/config.dev.php#L260). The production denylist is not public for what I hope are obvious reasons.
* In very _very_ rare cases, we may issue an IP-range-ban, blocking a wider range of IP addresses from creating new shorturls.

As you can see, we start with an extremely specific URL, and escalate to broader tools as necessary to protect the integrity of the service while minimizing the impact to innocent and valid users.

Regarding the link that came back on Spamhaus, we simply do not have the resources to review every single link that gets denied by our third party tools. Frankly, Spamhaus and Google Safe Browsing have had a remarkably good track record. If it is listed on Spamhaus or GSB, I am inclined to believe that it is for a valid reason. On a personal note, I have found that many crypto websites have been sources of spam and scams, particularly ones that are run on unmaintained WordPress instances. The URL you provided is a WordPress instance, although I cannot vouch for how well it is maintained.

I've been a member of the abuse team here for as long as it has existed (I'm fairly sure I was the first person that @relrod gave the ability to disable shorturls) and since we implemented the Spamhaus and GSB checks, the number of abuse reports we receive has gone down significantly. If you have a recommendation for a more accurate URL reputation system, we would welcome any input.

**Comment by phuzion** [comment]
So, a couple of things:

* @relrod and I just found [and fixed](https://github.com/dagd/dagd/commit/0f9276ce096a8f42165b5dbebc1fe1380268c6ae) a small bug, where the 30 minute cache was actually interpreted as 30 hours. As a result of this bug, an old Spamhaus listing for that URL was kept in our cache longer than it should have. This fix has been deployed to the production site, and the cache has been dropped, so your URL should successfully shorten now. As a result, I am closing this issue as completed.
* In general, I trust the results of Google Safe Browsing and Spamhaus. However, it is very common for one website to have an actively malicious URL in its database while the other does not. This can be for a number of reasons, the least of which is that each service receives reports from various different sources around the internet. I dislike the idea of waiting to denylist a URL until all of our indicators of potential maliciousness reach a consensus that yes, this URL is bad. Websites frequently get hacked and have malicious content placed on them in under an hour, and it may take multiple hours or even days for such malicious activity to be reported to all of the reputation services we use.
* There are currently 11 websites in the production allowlist. These websites include Wikipedia, Google and others with excellent reputations of handling abuse reports. They are long-established websites, with real companies and real people behind them. I can pick up a telephone and call someone at a Google NOC, I can speak to someone at Wikimedia's office, etc. The website you are requesting to be allowlisted appears to be some news website focusing on cryptocurrency. Although I did not do extensive research, I was not able to immediately find anything that provided evidence that they are a reputable news organization. As a result of this, and the fact that the bug that was erroneously reporting the website as denylisted has been fixed, I am not going to add that website to the allowlist for da.gd.

**Comment by relrod** [comment]
## Blacklisted URL

Hello and thanks for reaching out to the da.gd team!

The URL you have asked about is blocked by one of da.gd's upstream URL blacklist filters. It is rare that we make exceptions to these filters.

The URL you inquired about has been blacklisted by the following source:


```
Blacklist source: shorten.dnsbl [.dbl.spamhaus.org]
```

If you believe this to be in error, we encourage you to reach out to the service mentioned above and ask them to de-list the site in question, or to reach out to the administrators of the site in question and ask them to look into the issue.
